project:
  type: website
  output-dir: docs

website:
  title: "Mini Documentation Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: article1.qmd
        text: Article 1
      - href: article2.qmd
        text: Article 2
      - href: article3.qmd
        text: Article 3

format:
  html:
    theme: cosmo
    toc: true
